name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
      - run: ./mvnw deploy -e -B -V
        env:
          RESOLVER_GPG_KEY: ${{ secrets.RESOLVER_GPG_KEY }}
          RESOLVER_GPG_KEY_PASS: ${{ secrets.RESOLVER_GPG_KEY_PASS }}
    
